{
 "title": "PIED-LMS-Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "instances", "query": "label_values(up, instance)" }
  ]
 },
 "panels": [
  {
   "title": "Backend Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pied-lms-backend\"} | json | line_format \"[{{.Timestamp}}] {{.Level}} | {{.Message}}\""
    }
   ]
  },
  {
   "title": "Frontend Logs (Client-side)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"pied-lms-backend\", Source=\"Frontend\"} | json | line_format \"[{{.Timestamp}}] {{.Level}} | {{.Message}}\""
    }
   ]
  },
  {
   "title": "Avg Response Time (Duration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{instance=~\"$instances\"}[$interval])) by (endpoint) / sum(rate(http_request_duration_seconds_count{instance=~\"$instances\"}[$interval])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API Request Rate (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_received_total{instance=~\"$instances\"}[$interval])) by (endpoint, method, code)",
     "legendFormat": "{{method}} {{endpoint}} ({{code}})"
    }
   ]
  },
  {
   "title": "Current Active Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_in_progress{instance=~\"$instances\"}",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "Backend Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=~\"$instances\"}",
     "legendFormat": "Memory Used"
    }
   ]
  }
 ]
}