version: "3"

vars:
  # Point from the .slnx file to the .csproj
  PROJECT_PATH: "Src/PIED-LMS.API/PIED-LMS.API.csproj"
  DOPPLER: "doppler run --"

tasks:
  dev:
    desc: "Run API with Hot Reload"
    cmds:
      - "{{.DOPPLER}} dotnet watch run --project {{.PROJECT_PATH}}"

  test:
    desc: "Run all tests in the solution"
    cmds:
      - "{{.DOPPLER}} dotnet test"

  migrate:
    desc: "Update DB"
    cmds:
      - "{{.DOPPLER}} dotnet ef database update --project {{.PROJECT_PATH}}"

  clean:
    desc: "Clean all bin/obj in the backend"
    cmds:
      - find . -type d \( -name "bin" -o -name "obj" \) -exec rm -rf {} +

  status:
    desc: "See which project/config Doppler is connected to"
    cmds:
      - doppler configure

  list:
    desc: "List all available tasks"
    cmds:
      - go-task --list
