// Export all interfaces
export * from "./api.interface";
export * from "./axios.interface";
export * from "./auth/auth.interface";
export * from "./room/room.interface";
export * from "./user/user.interface";
export * from "./question/question.interface";
export * from "./testcase/testcase.interface";
export * from "./leaderboard/leaderboard.interface";
export * from "./exam/exam.types";
